import type { Metadata } from "next";
import "./globals.css";
import { AppBar } from "@/components/appBar/component";
import styles from "./layout.module.css";
import classNames from "classnames";
import { ibmPlexMono } from "./fonts";
import { Footer } from "@/components/footer/component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={classNames(ibmPlexMono.className, styles.root)}>
        <AppBar />
        {children}
        <div id="modal-container" />
      </body>
    </html>
  );
}
